# Generated by Django 5.1.2 on 2024-11-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
