# Generated by Django 5.1.2 on 2024-11-12 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_visible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
    ]
